name: "A11: scheduled scrape & PR"

on:
  schedule:
    - cron: '30 22 * * *'  # 07:30 JST
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  scrape-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ★毎回、固定ブランチに main を取り込む（CI定義のズレ防止）
      - name: Sync fixed branch with main
        run: |
          git fetch origin
          git checkout -B chore/daily-scrape origin/chore/daily-scrape || git checkout -B chore/daily-scrape
          git merge origin/main --no-edit || true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps for scraping
        run: |
          pip install -r requirements.txt || true
          pip install requests beautifulsoup4 lxml
          mkdir -p data

      - name: Run scraper
        run: python automation/scrape_titles.py

      - name: Create or update fixed PR
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/daily-scrape
          base: main
          title: 'chore: daily scrape'
          commit-message: 'chore: daily scrape'
          body: 'Automated daily scrape'
          labels: automation
          delete-branch: false
