name: CI notify PR on success

on:
  workflow_run:
    workflows: ["CI"]         # <- あなたの CI のワークフロー名
    types: [completed]

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ci-notify
  cancel-in-progress: true

jobs:
  notify:
    # CI が成功 かつ A11 の固定ブランチだけを対象にする
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'chore/daily-scrape'
    runs-on: ubuntu-latest
    steps:
      - name: 'Find open PR for chore/daily-scrape'
        id: find_pr
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const branch = context.payload.workflow_run.head_branch; // 'chore/daily-scrape'
            const prs = await github.rest.pulls.list({
              owner, repo, state: 'open',
              head: `${owner}:${branch}`,
              per_page: 1
            });
            if (prs.data.length === 0) {
              core.notice(`No open PR for ${branch}. Skipping comment.`);
              core.setOutput('pr_number', '');
              return;
            }
            core.setOutput('pr_number', String(prs.data[0].number));

      - name: 'Comment to PR'
        if: steps.find_pr.outputs.pr_number != ''
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.find_pr.outputs.pr_number }}
          RUN_URL:   ${{ github.event.workflow_run.html_url }}
          BRANCH:    ${{ github.event.workflow_run.head_branch }}
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const issue_number = Number(process.env.PR_NUMBER);
            const body = [
              `✅ CI passed for \`${process.env.BRANCH}\`.`,
              ``,
              `• Run: ${process.env.RUN_URL}`
            ].join('\n');
            await github.rest.issues.createComment({ owner, repo, issue_number, body });
