name: CI notify PR on success

on:
  workflow_run:
    workflows: ["CI"]        # ci.yml が完了したら起動
    types: [completed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  notify:
    # CI が成功 かつ 対象ブランチが chore/daily-scrape のときだけ実行
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'chore/daily-scrape' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Find open PR (head chore/daily-scrape)"
        id: find
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          PR_NUMBER=$(gh pr list --repo "$GITHUB_REPOSITORY" --state open --head chore/daily-scrape --json number --jq '.[0].number')
          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "found=true"  >> $GITHUB_OUTPUT
            echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Post comment to PR
        if: steps.find.outputs.found == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}"
          gh issue comment ${{ steps.find.outputs.number }} --body "✅ CI succeeded for \`chore/daily-scrape\`. [View run]($RUN_URL)"

      - name: No open PR - skip notify
        if: steps.find.outputs.found != 'true'
        run: echo "No open PR (chore/daily-scrape). Skipping."
