name: CI notify PR on success

on:
  workflow_run:
    workflows: ["CI"]     # CI が終わったときだけ起動
    types: [completed]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  notify:
    # CI が成功 かつ chore/daily-scrape の時だけ通知
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'chore/daily-scrape'
    runs-on: ubuntu-latest
    steps:
      - name: Comment to PR that CI finished
        uses: actions/github-script@v7
        with:
          script: |
            const run   = context.payload.workflow_run;       // ← ここがポイント
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            core.info(`CI run ${run.id} on ${run.head_branch} (${run.conclusion})`);

            // 開いている PR（head: owner:chore/daily-scrape, base: main）を探す
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${run.head_branch}`, base: 'main'
            });

            if (!prs.length) {
              core.info('No open PR from chore/daily-scrape. Skip.');
              return;
            }

            const pr = prs[0];
            const body = `✅ CI passed for \`${run.head_branch}\`.\n\n[View run](${run.html_url})`;
            await github.rest.issues.createComment({ owner, repo, issue_number: pr.number, body });
