name: CI notify PR on success

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: read
  pull-requests: write

jobs:
  notify:
    # CI が成功 かつ 対象ブランチが chore/daily-scrape のときだけ動く
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'chore/daily-scrape' }}
    runs-on: ubuntu-latest
    steps:
      - name: Show event (debug)
        run: echo '${{ toJson(github.event) }}'

      - name: Find open PR for this branch
        id: find
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.workflow_run.head_branch;
            const owner  = context.repo.owner;
            const repo   = context.repo.repo;

            // このブランチを head に持つ Open PR を取得
            const prs = await github.paginate(github.rest.pulls.list, {
              owner, repo, state: 'open', head: `${owner}:${branch}`,
              per_page: 100
            });

            core.setOutput('count', String(prs.length));
            if (prs.length > 0) core.setOutput('number', String(prs[0].number));

      - name: No PR → gracefully skip
        if: ${{ steps.find.outputs.count == '0' }}
        run: echo "No open PR for this branch. Skip."

      - name: Comment to PR
        if: ${{ steps.find.outputs.count != '0' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr    = Number('${{ steps.find.outputs.number }}');
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const runUrl = context.payload.workflow_run.html_url;
            const branch = context.payload.workflow_run.head_branch;

            await github.rest.issues.createComment({
              owner, repo, issue_number: pr,
              body: `✅ CI succeeded for \`${branch}\`.\n\n[View run](${runUrl})`
            });
