name: "CI notify PR on success"

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  notify:
    name: "Notify PR when CI passed"
    # CI が success かつ chore/daily-scrape のときだけ動く
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'chore/daily-scrape'
    runs-on: ubuntu-latest
    steps:
      - name: "Find open PR for chore/daily-scrape"
        id: find
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const head = `${owner}:chore/daily-scrape`;
            const prs = await github.paginate(github.rest.pulls.list, { owner, repo, state: 'open', head });
            core.info(`open PRs for ${head}: ${prs.length}`);
            if (prs.length === 0) { core.setOutput('pr_number', ''); return; }
            core.setOutput('pr_number', String(prs[0].number));

      - name: "Skip if PR not found"
        if: steps.find.outputs.pr_number == ''
        run: echo "No open PR for chore/daily-scrape; nothing to notify."

      - name: "Comment to PR"
        if: steps.find.outputs.pr_number != ''
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ steps.find.outputs.pr_number }}
        with:
          script: |
            const {owner, repo} = context.repo;
            const pr = Number(process.env.PR_NUMBER);
            const run = context.payload.workflow_run;
            const sha = run.head_sha.slice(0,7);
            const body = [
              `✅ CI passed for \`${run.head_branch}\` (@ ${sha})`,
              ``,
              `CI run: ${run.html_url}`,
            ].join("\n");
            await github.rest.issues.createComment({ owner, repo, issue_number: pr, body });
