name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install ruff pytest-cov

      - name: Create .env for tests
        run: |
          echo "DB_URL=postgresql://user:pass@localhost:5432/sampledb" > .env
          echo "API_KEY=devtoken" >> .env

      - name: Lint & format (ruff)
        run: |
          ruff format --check .
          ruff check .

      - name: Type check (mypy)
        run: mypy .

      - name: Run tests with coverage (pytest-cov)
        run: |
          pytest -q --cov=. --cov-report=term-missing:skip-covered --cov-fail-under=80
