name: "CI / test"

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install ruff
        run: pip install ruff
      - name: Ruff
        run: ruff check .

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install mypy & deps
        run: |
          pip install -r requirements.txt || true
          pip install mypy pandas-stubs
      - name: mypy
        run: mypy .

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11','3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          pip install -r requirements.txt || true
          pip install pytest pytest-cov
      - name: pytest
        run: pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=term-missing

  notify:
    name: Notify on PR (CI passed)
    if: ${{ success() && github.event_name == 'pull_request' }}
    needs: [lint, typecheck, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            if (!pr) {
              core.info('No PR context; skip.')
              return
            }
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `✅ CI passed for \`${pr.head.ref}\`. [View run](${runUrl})`
            })
