name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt mypy httpx

      - name: Create .env for tests
        run: |
          echo "DB_URL=postgresql://user:pass@localhost:5432/sampledb" > .env
          echo "API_KEY=devtoken" >> .env

      - name: Type check (mypy)
        run: mypy .

      - name: Run tests (pytest)
        run: pytest -q
